optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0

scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 25
    gamma: 0.1

loss:
  _target_: torch.nn.CrossEntropyLoss

epochs: 32