  dataset_url: "https://www.robots.ox.ac.uk/~vgg/data/flowers/17/17flowers.tgz"
  archive_filename: "17flowers.tgz"
  root_dir: "../dataset"
  extract_dir: "../dataset/raw"
  processed_data_dir: "../dataset/processed"
  txt_file: "../dataset/raw/jpg/files.txt"
  images_per_class: 80
  image_extension: "jpg"
  train_split: 0.6
  val_split: 0.2
  test_split: 0.2
  seed: 42