defaults:
  - _self_

dataset:
  root_dir: "../dataset/processed"

  # Transforms configuration for each split
  transforms:
    train:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.Resize
          size: [224, 224]
        - _target_: torchvision.transforms.ToTensor

    val:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.Resize
          size: [224, 224]
        - _target_: torchvision.transforms.ToTensor

    test:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.Resize
          size: [224, 224]
        - _target_: torchvision.transforms.ToTensor